Endpoint exports
alma/alma-python-client pull request #4
Opened 2020-01-30 21:46 UTC by jssuzanne

Ajoute une api minimaliste sur l'export des payements sous format csv.

```
alma = Client(api_key)
export = alma.exports.create(export_type='payments', start=start, end=end)
sleep(5)
fp = alma.exports.get_file(export.id)
```

The waiting time is necessary to the file is available on the server

2020-01-31 09:31 UTC, Natim commented on alma/endpoints/exports.py
> +        data = dict(type=export_type)
```suggestion
        data = {"type": export_type}
```

2020-01-31 15:33 UTC, olance requested changes

2020-01-31 15:33 UTC, olance commented on alma/endpoints/exports.py
> +            raise ExportsException("%s is not an availale type" % export_type)
```suggestion
            raise ExportsException(f"{export_type} is not an available type")
```

2020-01-31 15:33 UTC, olance commented on alma/endpoints/exports.py
> +EXPORT_TYPES = ['payments', 'accounting', 'accounting_for_payout']
I'd rather have an enum type than string constants, as they are not directly referenceable

2020-01-31 15:33 UTC, olance commented on alma/endpoints/exports.py
> +    def get_file(self, export_id: str = None, export_format: str = 'csv'):
```suggestion
    def get_file(self, export_id: str = None, export_format: str = 'csv'):
```

Could we also have an enum type for the `export_format`?
It makes it self-documenting that CSV, XLSX and PDF (on some specific exports) formats are supported

2020-01-31 15:33 UTC, olance commented on alma/endpoints/exports.py
> +        return BytesIO(response.resp.text.encode())
Let's work with bytes directly, so that we handle binary files correctly

```suggestion
        return BytesIO(response.resp.content)
```

2020-02-04 11:16 UTC, Natim commented on alma/endpoints/exports.py
> +            for attribute, value in filters.items():
```suggestion
            args.update(filters)
```

2020-02-04 11:17 UTC, Natim approved these changes
Thank you for your work on this.
I have one last nitpick but otherwise it looks good to me.

2020-02-07 21:54 UTC, olance approved these changes
Thanks @jssuzanne, LGTM! 👍

2020-02-07 21:56 UTC, merged

2020-02-07 21:56 UTC, olance commented
and thanks @Natim for the heavy lifting on the lib :)